### ISSUE TITLE
Changing location of twitter notification in the top right. 

### ISSUE THREAD

**Issue by Parker5701** [N3MTV/gcphone#129]
Hi i'm trying to find where I can change the location of the twitter notification as our chat box blocks it.

**Comment by Gannon001** [comment]
Add in /gcphone/html/static/css/app.css
```css
.notifications {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
}
```
